### ISSUE TITLE
flatpak version?

### ISSUE THREAD

**Issue by git-Hmmm** [agam778/MS-365-Electron#100]
It would be cool, if you could publish this on flathub.org too, nowadays flatpaks are more preferred by the community.

**Comment by agam778** [comment]
There's a PR open from long time, but they aren't responding - https://github.com/flathub/flathub/pull/3166

I'll update the flatpak package after the v0.8.0 update, and will ask them to take some action related to publishing it.

**Comment by git-Hmmm** [comment]
@agam778 why closed the flatpak pr?

**Comment by agam778** [comment]
Nah, no further plans to support flatpak. Not having the time to do that

But if someone wants to maintain it they can do it.
