### ISSUE TITLE
The repo is updated but the about link still points to old url, resulting in 404.

### ISSUE THREAD

**Issue by git-Hmmm** [agam778/MS-365-Electron#101]
![image](https://user-images.githubusercontent.com/102938585/203674060-3e8bc65d-41ae-4617-9e3f-28add8d6749a.png)
![image](https://user-images.githubusercontent.com/102938585/203674163-6f9eb5ac-f6ff-482a-b6dc-f036df1df095.png)
it should be replaced with this one: https://agam778.github.io/MS-365-Electron

**Comment by agam778** [comment]
Ah yep, I'll update that.

Actually there are many things pending right now, because of the rebrand.

Thanks anyways
