### ISSUE TITLE
Account does not save.

### ISSUE THREAD

**Issue by FormalSnake** [agam778/MS-365-Electron#104]
When I close the Application, and start it again, I will be logged out.

**Comment by agam778** [comment]
Are you using a personal account or an Enterprise account? What OS are you using? Weird because this never happened to me. Are you using the latest version 0.8.0? Can you explain your issue in detail?

**Comment by agam778** [comment]
Hmm, I really don't know what the issue is, and right now my exams are going on, so I'll check and tell about it later. Does the released build for macOS not work?

**Comment by FormalSnake** [comment]
Its just that the release is from november, but the source from december.

**Comment by FormalSnake** [comment]
Still the same issue.

**Comment by agam778** [comment]
Can you provide the logs?

In menu bar, click on Applications, open logs folder and send the log

**Comment by FormalSnake** [comment]
[main.log](https://github.com/agam778/MS-365-Electron/files/10685722/main.log)

**Comment by FormalSnake** [comment]
No problem!

**Comment by agam778** [comment]
Hey, so I tried to reproduce this on Windows 11 and Arch Linux, and for me it's working perfectly fine. Not sure why is it happening for you, but I'll see if I can get a macOS user for testing that.

**Comment by FormalSnake** [comment]
All right. :)

**Comment by agam778** [comment]
A guy tested the November build for me, and for him it's working perfectly fine. Not sure why it is occurring for you.

**Comment by FormalSnake** [comment]
Oh well, I can just use the web version.
