### ISSUE TITLE
Unable to use school (educational)  account

### ISSUE THREAD

**Issue by WahabDev12** [agam778/MS-365-Electron#105]
First of all, just wanna thank you for creating this application. Totally love it.
I was wondering if I could sign in with my school ( .edu ) account. Anytime I use an email that ends with  .edu domain to sign in, i get this message "Account not found... Create a new one". 

Is there a way around this?

**Comment by WahabDev12** [comment]
oops...solved it

**Comment by coffandro** [comment]
how did you solve it?

**Comment by PACHAKUTlQ** [comment]
> how did you solve it?

First login with personal account. Then on the home page click the avatar on the top-right, and click "Sign in with a different account", then you can sign in with your school account.

**Comment by agam778** [comment]
> > how did you solve it?
> 
> First login with personal account. Then on the home page click the avatar on the top-right, and click "Sign in with a different account", then you can sign in with your school account.

Even though this works, there's a better option, basically using 2 separate profiles for personal accounts and work/edu accounts, which would prevent logging in every time you switch from edu/work to personal and vice versa.

![image](https://github.com/user-attachments/assets/02925bb0-1509-4101-8b53-f63aaa7da128)
