### ISSUE TITLE
Tabs its possible?

### ISSUE THREAD

**Issue by iza001** [agam778/MS-365-Electron#108]
Is it possible to use tabs in the same window? This would make the work more comfortable, although I don't know if electron allows it.

**Comment by agam778** [comment]
Nope - It isn't possible when you're loading a remote URL

**Comment by FormalSnake** [comment]
It is possible using [electron-tabs](https://github.com/brrd/electron-tabs)
They demonstrate it loading a remote URL, and they look nice.

**Comment by agam778** [comment]
It's pretty much dead though, no? I'll still check once

**Comment by FormalSnake** [comment]
the community is still active.
