### ISSUE TITLE
"Hide Menu Bar" is not working

### ISSUE THREAD

**Issue by gazm2k5** [agam778/MS-365-Electron#122]
"Hide Menu Bar" is not working.
I'm running Debian 12 and version MS-365-Electron 0.9.0

**Comment by agam778** [comment]
Exactly how? Have you tried restarting the app?

**Comment by gazm2k5** [comment]
Yes I have tried that, no luck. I installed version 0.8 with apt package manager and then installed 0.9 with snap, and uninstalled 0.8 with apt. Not sure if I messed anything up by doing that.

**Comment by agam778** [comment]
Alright, I'll try to reproduce once I have access to my laptop.

**Comment by agam778** [comment]
Oh, and btw, can you install from the .deb file, try to hide the menu and send me the logs? 

[In the menu, MS-365-Electron -> View Logs (or something similar), get the log file and attach it here]

Thanks
