### ISSUE TITLE
File download error (or some sort of) 

### ISSUE THREAD

**Issue by JGMelon22** [agam778/MS-365-Electron#130]
When you try to download a file, let's say from OneDrive, it works but gives a JavaScript error like the one below:

<img src="https://github.com/agam778/MS-365-Electron/assets/73988556/10effc9e-366a-4c1f-a3c4-48aff1b1b2ba" width="300" height="200"/>

<h4>Steps to reproduce:</h4>
1- Launch the program; </br>
2- Navigate to OneDrive; </br>
3- Select a file and download it </br></br>

<span>Extra info:</span>
- Arco Linux 
- AUR Package (MS-365-Electron - v0.9.0)

**Comment by agam778** [comment]
oh lmao yeah I've faced it here, iirc I've fixed it in the source code (I'll check and let you know)

In the meantime, there's no temporary fix for that. Sorry

**Comment by agam778** [comment]
actually, I haven't fixed that, really sorry for that.

Can't do anything about that right now, you'll have to wait for a month since I have my exams going right now.

**Comment by JGMelon22** [comment]
> actually, I haven't fixed that, really sorry for that.
> 
> Can't do anything about that right now, you'll have to wait for a month since I have my exams going right now.

No worries, mate. Good luck at the exams :)

**Comment by agam778** [comment]
working on this right now!

**Comment by agam778** [comment]
Done! (https://github.com/agam778/MS-365-Electron/commit/f98d304b40e8106c2f98a9d6eb3ac7393c39eca9)

Actually, I don't have a linux machine right now, so can you please install ms-365-electron-git and test if it isn't showing any error now? Thanks

**Comment by JGMelon22** [comment]
> Done! ([f98d304](https://github.com/agam778/MS-365-Electron/commit/f98d304b40e8106c2f98a9d6eb3ac7393c39eca9))
> 
> Actually, I don't have a linux machine right now, so can you please install ms-365-electron-git and test if it isn't showing any error now? Thanks

You mean clone the repo and build here? If so, sure. I know it's sounds stupid question, but I've been having some dogs day :/

**Comment by agam778** [comment]
nah, just `yay -S ms-365-electron-git`, it'll do everything for you

or just let me know if you can't, I'll set up a virtual machine

**Comment by JGMelon22** [comment]
Seams it's forcing me to install `yarn`  however I do have it already. Tried to add `--ignore=yarn` flag, no success what so ever. Will try to install it on a spare machine as I can not change many things here at my production one. You're the best, mate :D

**Comment by agam778** [comment]
It'll uninstall yarn after the app's installed, actually it installs yarn v1 from AUR

**Comment by JGMelon22** [comment]
> It'll uninstall yarn after the app's installed, actually it installs yarn v1 from AUR

Just to give an update: it does works from `-git`. I gave a shot on a spared machine and worked like a charm, no error download message what so ever :)

**Comment by agam778** [comment]
Cool! Thanks for testing, I'll release a new build in few days, after fixing a few things

Closing the issue now
