### ISSUE TITLE
Add desktop file associations

### ISSUE THREAD

**Issue by zt64** [agam778/MS-365-Electron#158]
This program is really nice, and comes in handy quite often. One thing I do wish it did have though is the ability to open up office files like docx pptx, xlsx in their respective program. In theory it should just be identifying the file, opening the program for it and automatically opening from the file.
Would be a really nice addition to have this I feel

**Comment by agam778** [comment]
Hi! I am sorry, but I need to prioritize my studies at the moment due to personal reasons, and my exams are approaching as well. I'll still try my best to find some time and fix this. I hope you understand.

**Comment by PACHAKUTlQ** [comment]
Hi! This would be very convenient. May you reconsider adding this feature?

**Comment by agam778** [comment]
I'll think about it once I get the time to work on this app.

**Comment by PACHAKUTlQ** [comment]
> I'll think about it once I get the time to work on this app. That wouldn't be any soon though.

Thx. But unfortunately I just searched and found Office 365 online doesn't support editing local files, which is a pity. I expected something to do with the js file api to access local files but it doen't seem to support that. So I guess adding this feature could be hard and involves some reverse-engineering of the 365 desktop app or reversing the editing capability of the online 365.

**Comment by agam778** [comment]
> On Windows

Well, I don't think most of the Windows users would prefer an Electron app over the native suite (including me, lol). Still, I'll have a look, thanks.
