### ISSUE TITLE
BUG: Auto hide for app menu only works with main homepage

### ISSUE THREAD

**Issue by jobs-git** [agam778/MS-365-Electron#162]
See below, the even when the Hide Menu Bar is enabled, the OneDrive page still has menu bar.

When sites are opened in the same window, this issue does not happen

![image](https://github.com/agam778/MS-365-Electron/assets/13552004/17e821df-b1f0-4e7b-a5e6-882da1b1314b)

**Comment by agam778** [comment]
Hi! I am sorry, but I need to prioritize my studies at the moment due to personal reasons, and my exams are approaching as well. I'll still try my best to find some time and fix this. I hope you understand.

**Comment by agam778** [comment]
Hi! I've fixed this issue, but I _probably_ won't release a stable version any sooner.
