### ISSUE TITLE
Add a separate app Windows365 to quickly open a specific Windows 365 instance from the front page

### ISSUE THREAD

**Issue by MurzNN** [agam778/MS-365-Electron#201]
Will be good to add a separate app "Windows365" to allow quick opening it from the front page of the app. 

Now to open it I should go to the "Apps" side, choose there the "Windows 365" (that will be opened in a new window), then click on the "Open in browser" button there with getting a new window again, and only there - got the Windows365 interface.

**Comment by agam778** [comment]
Windows 365 is not a part of Microsoft 365, so it will not be added. 
Also I would recommend you to use a browser instead of this app for Windows 365.
