### ISSUE TITLE
void linux

### ISSUE THREAD

**Issue by xHyroM** [agam778/MS-365-Electron#214]
Created voidlinux pkg, you can mention it if you want :D https://github.com/xHyroM/void-packages/tree/main/srcpkgs/ms-365-electron

https://void-repo.xhyrom.dev/

**Comment by agam778** [comment]
That's great! Thanks a lot :)

I'll mention it in the README soon.

**Comment by agam778** [comment]
Hey! Sorry for the delay.

Can you please rename the https://github.com/xHyroM/void-packages/blob/main/srcpkgs/ms-365-electron/files/office to ms-365-electron?

**Comment by xHyroM** [comment]
done :+1:

**Comment by agam778** [comment]
Shouldn't [this](https://github.com/xHyroM/void-packages/blob/48ffdc0e9dc808175f785fe85cf293ec547db81b/srcpkgs/ms-365-electron/template#L9) be changed to ms-365-electron as well?

**Comment by xHyroM** [comment]
you're right, fixed

**Comment by agam778** [comment]
Added! I hope the instructions are correct. I am closing the issue.
