### ISSUE TITLE
Open website in the same window not work

### ISSUE THREAD

**Issue by PewPew06ProYT** [agam778/MS-365-Electron#219]
![new2](https://github.com/agam778/MS-365-Electron/assets/92674862/c3efd0d4-5950-4ea3-a1af-09bf6829573b)
![new](https://github.com/agam778/MS-365-Electron/assets/92674862/67f83644-e116-4126-8f7b-71eb8ef62cda)

**Comment by agam778** [comment]
Try View -> Reload or Force Reload, I hope that helps.
