### ISSUE TITLE
Add option to "Open Websites in Default Browser"?

### ISSUE THREAD

**Issue by fabern** [agam778/MS-365-Electron#240]
Hi agam778,

Thanks for providing MS-365-Electron. It integrates really well into my workflow to have a separate Window for Outlook similar to an email client.

I would love to see the option that links are opened with the default browser instead of the MS-365-Electron instance. This would bring it even closer to a separate mail client.
Would an additional option like this be possible?

E.g. extending the options to:
- **Open Websites in Default Browser**
- Open Websites in New Windows
- Open Websites in the Same Window

Thanks,
Fabian

**Comment by agam778** [comment]
Do you want this option for Outlook only or other apps as well?

**Comment by fabern** [comment]
Excellent, thanks so much for adding this!

How can I get the update? 
My first install was via snap. This doesn't seem to be updated.
I'm now trying to build the code locally, but am getting an error:
```
$ git clone https://github.com/agam778/MS-365-Electron.git
$ cd MS-365-Electron
$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

**Comment by agam778** [comment]
I'll be releasing the new update, probably in a week or so, but you can download the developer version from here, which I guess is stable enough:
https://github.com/agam778/MS-365-Electron/actions/runs/10346482041

Download ubuntu-latest-dist and then install it using either deb/rpm/snap depending on whatever you are using currently.

**Comment by fabern** [comment]
Thanks, I have now installed the developer version you linked.
I can see that the option is now activated, however it still opens links within the app. 
E.g. the following link from a GitHub email in Outlook, does not open with my default browser (Firefox) on Ubuntu 22.04:

`<a href="..." target="_blank" rel="noopener noreferrer" data-auth="Verified" originalsrc="..." shash="..." title="Original URL: https://github.com/.... Click or tap if you trust this link." data-linkindex="1">view it on GitHub<div></div></a>`

**Comment by agam778** [comment]
Does it work for other links? I don't have access to my laptop right now, so I will try to reproduce later.

**Comment by fabern** [comment]
Okay, it appears to work in:
- Word
- Excel
- Powerpoint
In those apps I could activate/deactivate the desired behavior with the menu option.

But not in Outlook:
There I tested a variety of different emails in my inbox. None of them opened externally.

Thanks for looking into this. But no rush... it is not urgent.

**Comment by agam778** [comment]
![CleanShot 2024-08-13 at 17 20 23](https://github.com/user-attachments/assets/923a3766-27e8-40ba-8b1c-08cfc2d65bac)

It cannot reproduce on Fedora with the app installed via Snap. I just checked if this option is enabled (it's enabled by default), and then I opened Outlook and opened a link in my mail, which opened in my default browser (Firefox)

**Comment by ljudina** [comment]
What happened with `Open External Links in Default Browser`? It does not show in version 2.0.0

![Screenshot from 2024-12-04 12-17-26](https://github.com/user-attachments/assets/b92139ad-577c-43c4-a878-6b0894ff7f83)

**Comment by Neunerlei** [comment]
> What happened with `Open External Links in Default Browser`? It does not show in version 2.0.0

Looks like Version 2.0.0 has been built on May 8, which was before this issue has been marked as resolved.
The repository owner mentioned using a build artifact to get that feature, but sadly all of them seem to have timed out. 
But you can always compile the version yourself :)

Cheers!

**Comment by agam778** [comment]
Sorry guys, I've been a bit busy lately hence unable to release any new updates.

Triggered a new CI build, new artifacts can be downloaded from https://github.com/agam778/MS-365-Electron/actions/runs/12562654562

I'll try my best to release a new update in a month or two. Thanks.

**Comment by Neunerlei** [comment]
@agam778 Thank you! And a happy new year to you and your loved ones :fireworks:

**Comment by agam778** [comment]
> @agam778 Thank you! And a happy new year to you and your loved ones :fireworks: 

You're welcome man. Happy new year! 🎊
