### ISSUE TITLE
Account doesn't exist

### ISSUE THREAD

**Issue by marcosnava** [agam778/MS-365-Electron#243]
When I try to logon with my account I receive account doesn't exist, but when I try to logon Microsoft 365 site it works.

I use an enterprise account and I've selected work/schooll account

**Comment by marcosnava** [comment]
All of a sudden it worked... Sorry.

**Comment by agam778** [comment]
Since it's fixed, may I close the issue now?

**Comment by marcosnava** [comment]
Sure!

Em dom., 21 de jul. de 2024, 04:51, Agampreet Singh <
***@***.***> escreveu:

**Comment by bryce-hoehn** [comment]
<img width="1812" height="990" alt="Image" src="https://github.com/user-attachments/assets/6cd340bd-d4ca-4b11-94fe-63be1601cb2b" />

I am experiencing the same issue with my university account on the latest Appimage release.

**Comment by agam778** [comment]
> <img width="1812" height="990" alt="Image" src="https://github.com/user-attachments/assets/6cd340bd-d4ca-4b11-94fe-63be1601cb2b" />
> 
> I am experiencing the same issue with my university account on the latest Appimage release.

Did you completely close the app and open it again after switching?
