### ISSUE TITLE
Ability to open local files

### ISSUE THREAD

**Issue by DeviDarkL** [agam778/MS-365-Electron#252]
Hello again,

I know this is probably impossible but is there a way to open a local file clicking on that file and upload and open it directly to MS-365-ELECTRON?

This would be THE killer feature :)

Thank you for doing this app,
Best regards

**Comment by agam778** [comment]
Yeah, that feature would be awesome, but the issue is that I'm currently quite busy and since this would require a lot of time, I might not be able to implement it right away. I'll definitely keep it in mind and implement it, if possible.
