### ISSUE TITLE
Gnome: Integrate minimze/maximize/close

### ISSUE THREAD

**Issue by DeviDarkL** [agam778/MS-365-Electron#260]
Hello again :)

Thank you for this awesome wrapper. It works really well. Since GNOME is one of the most used layouts of LINUX is it possible to integrate the minimize/maximize/close (title bar) in the office suite?

![printscreen](https://github.com/user-attachments/assets/bbbdee30-a405-465d-8a83-1a772816b6d8)

Cheers!

**Comment by agam778** [comment]
Thanks for the suggestion, I tried doing this once on macOS, but I couldn't complete it due to the lack of time. Also, as far as I know, this isn't possible on Linux.

So maybe I'll consider doing it someday later.
